site_name: Powermon Documentation
repo_url: https://github.com/jblance/powermon
theme:
  name: material
  # name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Usage: 
    - Usage: usage/usage.md
    - Config File: usage/config_file.md
    - Docker: usage/docker.md
    - Troubleshooting: usage/troubleshooting.md
  - Tutorials:
    - Daly BMS: tutorials/daly_bms.md
  - Code Reference: 
    - Development Logic: code_ref/development_logic.md
    - powermon: code_ref/powermon.md
  - Protocol Documentation:
    - Daly CANBus: protocol_docs/daly_can.md
    - Voltronic Power (PI16): protocol_docs/PI16.md
    - MPPsolar (PI30): protocol_docs/pi30.md
    - MPPsolar (PI30MAX): protocol_docs/pi30max.md
    - JKBMS SERIAL (JKSERIAL): protocol_docs/jkserial.md
    - JKBMS (JKV4): protocol_docs/jkv4.md
markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  # - toc:
  - mkdocstrings:
      default_handler: python
extra_css:
  - stylesheets/extra.css