# yaml config for powermon
# logging (DEBUG, INFO, WARNING, ERROR, CRITICAL)
debuglevel: INFO

device:
  id: test
  name: 1012LV-MK
  model: 1012LV-MK
  manufacturer: MPP-Solar
  port:
    path: /dev/hidraw0
    type: usb
    protocol: PI30

commands:
- command: Q1 #Must be in the protocol command list
  type: basic
  trigger:
    every: 30  # seconds
  outputs:
  - type: api_mqtt
    format: 
      type: simple

          
mqttbroker:
  name: localhost
  port: 1883
  username: null
  password: null

api:
  host: null
  port: null
  enabled: true
  log_level: null
  announce_topic: powermon/announce
  adhoc_topic: powermon/adhoc
  refresh_interval: 300

# daemon:
#   type: systemd
#   keepalive: 100

loop: null